-- Create emojis table
CREATE TABLE IF NOT EXISTS public.emojis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rarity TEXT DEFAULT 'common' CHECK (rarity IN ('common', 'rare', 'legendary')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create user_emojis table (inventory)
CREATE TABLE IF NOT EXISTS public.user_emojis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  emoji_id BIGINT NOT NULL REFERENCES public.emojis(id) ON DELETE CASCADE,
  acquired_at TIMESTAMPTZ DEFAULT NOW(),
  source TEXT DEFAULT 'checkin'
);

-- Enable RLS
ALTER TABLE public.emojis ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_emojis ENABLE ROW LEVEL SECURITY;

-- Policies
-- Emojis are viewable by everyone
CREATE POLICY "Emojis are viewable by everyone" ON public.emojis FOR SELECT USING (true);

-- User Emojis: users can see their own, or maybe everyone's? Let's say everyone can see others' collection for now, or just own.
-- Usually "my collection" is private or public profile. Let's allow select for all for now (social features).
CREATE POLICY "User emojis are viewable by everyone" ON public.user_emojis FOR SELECT USING (true);

-- Only system (service role) should insert/update/delete generally, but for simplicity we might rely on triggers.
-- If we use triggers, the trigger executes with the privileges of the function owner (usually postgres/admin) if SECURITY DEFINER is used.

-- Insert some initial emojis (You should update URLs after uploading images to Supabase Storage)
INSERT INTO public.emojis (name, url, rarity) VALUES
('Thumbs Up', 'https://placeholder.com/thumbsup.png', 'common'),
('Fire', 'https://placeholder.com/fire.png', 'common'),
('Star', 'https://placeholder.com/star.png', 'rare'),
('Trophy', 'https://placeholder.com/trophy.png', 'legendary')
ON CONFLICT DO NOTHING; -- No unique constraint on name yet, but good practice if we added one.

-- Function to reward emoji
CREATE OR REPLACE FUNCTION public.reward_emoji_on_checkin()
RETURNS TRIGGER AS $$
DECLARE
  random_emoji_id BIGINT;
BEGIN
  -- Select a random emoji
  -- Simple random selection. For weighted, we'd need more logic.
  SELECT id INTO random_emoji_id
  FROM public.emojis
  ORDER BY random()
  LIMIT 1;

  IF random_emoji_id IS NOT NULL THEN
    INSERT INTO public.user_emojis (user_id, emoji_id, source)
    VALUES (NEW.user_id, random_emoji_id, 'checkin');
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
DROP TRIGGER IF EXISTS on_checkin_created ON public.flag_checkins;
CREATE TRIGGER on_checkin_created
AFTER INSERT ON public.flag_checkins
FOR EACH ROW
EXECUTE FUNCTION public.reward_emoji_on_checkin();

-- Create storage bucket for emojis if it doesn't exist
-- Note: This requires permissions to insert into storage.buckets. 
-- Often managed via Dashboard, but we can try SQL.
INSERT INTO storage.buckets (id, name, public)
VALUES ('emojis', 'emojis', true)
ON CONFLICT (id) DO NOTHING;

-- Policy for storage: Public read
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'emojis' );

-- Policy for storage: Authenticated upload (or restrict to admin)
-- For now, let's allow authenticated users to upload if they need to (maybe not for emojis, usually admins).
-- We'll skip upload policy for users, assuming admins upload via dashboard.
