-- ============================================================
-- 批量结算相关表 - Polymarket 风格链上结算
-- ============================================================

-- 1. 结算批次表
CREATE TABLE IF NOT EXISTS public.settlement_batches (
  id TEXT PRIMARY KEY,
  chain_id INTEGER NOT NULL,
  market_address TEXT NOT NULL,
  fill_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending', -- pending, submitting, submitted, confirmed, failed
  tx_hash TEXT,
  block_number BIGINT,
  gas_used NUMERIC,
  error TEXT,
  retry_count INTEGER DEFAULT 0,
  submitted_at TIMESTAMPTZ,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 索引
CREATE INDEX IF NOT EXISTS settlement_batches_status_idx ON public.settlement_batches (status);
CREATE INDEX IF NOT EXISTS settlement_batches_market_idx ON public.settlement_batches (market_address, chain_id);
CREATE INDEX IF NOT EXISTS settlement_batches_tx_hash_idx ON public.settlement_batches (tx_hash);

-- 2. 失败的 fills 记录 (用于重试)
CREATE TABLE IF NOT EXISTS public.failed_fills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fill_id TEXT NOT NULL,
  batch_id TEXT REFERENCES public.settlement_batches(id),
  error TEXT,
  retry_count INTEGER DEFAULT 0,
  next_retry_at TIMESTAMPTZ,
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'failed_fills' AND column_name = 'chain_id'
  ) THEN
    ALTER TABLE public.failed_fills ADD COLUMN chain_id INTEGER;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'failed_fills' AND column_name = 'market_address'
  ) THEN
    ALTER TABLE public.failed_fills ADD COLUMN market_address TEXT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'failed_fills' AND column_name = 'payload'
  ) THEN
    ALTER TABLE public.failed_fills ADD COLUMN payload JSONB;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS failed_fills_batch_idx ON public.failed_fills (batch_id);
CREATE INDEX IF NOT EXISTS failed_fills_retry_idx ON public.failed_fills (next_retry_at) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS failed_fills_market_chain_idx ON public.failed_fills (chain_id, market_address);
CREATE UNIQUE INDEX IF NOT EXISTS failed_fills_fill_id_uq ON public.failed_fills (fill_id);

-- 3. Operator 配置表
CREATE TABLE IF NOT EXISTS public.operators (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id INTEGER NOT NULL,
  market_address TEXT NOT NULL,
  operator_address TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active', -- active, paused, deprecated
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (chain_id, market_address)
);

-- 4. 结算统计视图
CREATE OR REPLACE VIEW settlement_stats AS
SELECT 
  chain_id,
  market_address,
  COUNT(*) FILTER (WHERE status = 'pending') as pending_batches,
  COUNT(*) FILTER (WHERE status = 'submitted') as submitted_batches,
  COUNT(*) FILTER (WHERE status = 'confirmed') as confirmed_batches,
  COUNT(*) FILTER (WHERE status = 'failed') as failed_batches,
  SUM(fill_count) FILTER (WHERE status = 'confirmed') as total_fills_settled,
  SUM(gas_used) FILTER (WHERE status = 'confirmed') as total_gas_used,
  AVG(fill_count) FILTER (WHERE status = 'confirmed') as avg_batch_size,
  AVG(EXTRACT(EPOCH FROM (confirmed_at - submitted_at))) FILTER (WHERE status = 'confirmed') as avg_confirmation_time_sec
FROM public.settlement_batches
GROUP BY chain_id, market_address;

-- 5. 为 orders 表添加结算状态字段 (如果不存在)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'orders' AND column_name = 'settlement_status'
  ) THEN
    ALTER TABLE public.orders ADD COLUMN settlement_status TEXT DEFAULT 'pending';
    CREATE INDEX IF NOT EXISTS orders_settlement_status_idx ON public.orders (settlement_status);
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'orders' AND column_name = 'settlement_batch_id'
  ) THEN
    ALTER TABLE public.orders ADD COLUMN settlement_batch_id TEXT;
  END IF;
END $$;

-- 6. 为 trades 表添加结算关联 (如果不存在)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'trades' AND column_name = 'settlement_batch_id'
  ) THEN
    ALTER TABLE public.trades ADD COLUMN settlement_batch_id TEXT;
  END IF;
END $$;

-- 启用 RLS
ALTER TABLE public.settlement_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.failed_fills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.operators ENABLE ROW LEVEL SECURITY;

-- 公开读取策略
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'settlement_batches' AND policyname = 'Settlement batches are viewable by everyone') THEN
    CREATE POLICY "Settlement batches are viewable by everyone" ON public.settlement_batches FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'operators' AND policyname = 'Operators are viewable by everyone') THEN
    CREATE POLICY "Operators are viewable by everyone" ON public.operators FOR SELECT USING (true);
  END IF;
END $$;

-- 服务端写入策略 (仅 service_role)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'settlement_batches' AND policyname = 'Service can manage settlement batches') THEN
    CREATE POLICY "Service can manage settlement batches" ON public.settlement_batches 
    FOR ALL USING (auth.role() = 'service_role');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'failed_fills' AND policyname = 'Service can manage failed fills') THEN
    CREATE POLICY "Service can manage failed fills" ON public.failed_fills 
    FOR ALL USING (auth.role() = 'service_role');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'operators' AND policyname = 'Service can manage operators') THEN
    CREATE POLICY "Service can manage operators" ON public.operators 
    FOR ALL USING (auth.role() = 'service_role');
  END IF;
END $$;

-- 添加 Realtime
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'settlement_batches') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.settlement_batches;
  END IF;
END $$;

COMMENT ON TABLE public.settlement_batches IS '批量结算记录 - 追踪链上结算状态';
COMMENT ON TABLE public.failed_fills IS '失败的撮合记录 - 用于重试';
COMMENT ON TABLE public.operators IS 'Operator 配置 - 每个市场的链上结算者';
