-- 1. Trades table (Stores individual trades)
CREATE TABLE IF NOT EXISTS public.trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  network_id INTEGER NOT NULL, -- Chain ID
  market_address TEXT NOT NULL,
  outcome_index INTEGER NOT NULL,
  price NUMERIC NOT NULL, -- Stored as numeric for precision, but originating from uint256
  amount NUMERIC NOT NULL,
  taker_address TEXT NOT NULL,
  maker_address TEXT NOT NULL,
  is_buy BOOLEAN NOT NULL, -- Matches the Order's direction (Maker's direction)
  tx_hash TEXT NOT NULL,
  log_index INTEGER NOT NULL DEFAULT 0,
  fee TEXT,
  salt TEXT,
  block_number BIGINT NOT NULL,
  block_timestamp TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (tx_hash, log_index)
);

-- Indexes for trades
CREATE INDEX IF NOT EXISTS trades_market_outcome_idx ON public.trades (market_address, outcome_index, block_timestamp);
CREATE INDEX IF NOT EXISTS trades_tx_hash_idx ON public.trades (tx_hash);

-- 2. Candles table (Stores OHLCV data)
CREATE TABLE IF NOT EXISTS public.candles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  network_id INTEGER NOT NULL,
  market_address TEXT NOT NULL,
  outcome_index INTEGER NOT NULL,
  resolution TEXT NOT NULL, -- '1m', '15m', '1h', '4h', '1d'
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  volume NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL, -- Start time of the candle
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (network_id, market_address, outcome_index, resolution, time)
);

-- Indexes for candles
CREATE INDEX IF NOT EXISTS candles_query_idx ON public.candles (market_address, outcome_index, resolution, time DESC);

-- Enable RLS
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candles ENABLE ROW LEVEL SECURITY;

-- Public read access
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'trades' AND policyname = 'Trades are viewable by everyone') THEN
    CREATE POLICY "Trades are viewable by everyone" ON public.trades FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'candles' AND policyname = 'Candles are viewable by everyone') THEN
    CREATE POLICY "Candles are viewable by everyone" ON public.candles FOR SELECT USING (true);
  END IF;
END $$;

-- Add to Realtime
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'trades') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.trades;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'candles') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.candles;
  END IF;
END $$;

-- 3. Relayer ingest cursors (for idempotent log ingestion)
CREATE TABLE IF NOT EXISTS public.relayer_ingest_cursors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chain_id INTEGER NOT NULL,
  cursor_key TEXT NOT NULL,
  last_processed_block BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (chain_id, cursor_key)
);

CREATE INDEX IF NOT EXISTS relayer_ingest_cursors_chain_idx
  ON public.relayer_ingest_cursors (chain_id);

ALTER TABLE public.relayer_ingest_cursors ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'relayer_ingest_cursors' AND policyname = 'Relayer ingest cursors are viewable by everyone') THEN
    CREATE POLICY "Relayer ingest cursors are viewable by everyone" ON public.relayer_ingest_cursors FOR SELECT USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'relayer_ingest_cursors' AND policyname = 'Service can manage relayer ingest cursors') THEN
    CREATE POLICY "Service can manage relayer ingest cursors" ON public.relayer_ingest_cursors
    FOR ALL USING (auth.role() = 'service_role');
  END IF;
END $$;
