CREATE TABLE IF NOT EXISTS public.deposit_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  proxy_address TEXT NOT NULL,
  chain_id INTEGER NOT NULL,
  token_address TEXT NOT NULL,
  tx_hash TEXT NOT NULL,
  log_index INTEGER NOT NULL DEFAULT 0,
  block_number BIGINT NOT NULL,
  block_timestamp TIMESTAMPTZ,
  from_address TEXT NOT NULL,
  to_address TEXT NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (tx_hash, log_index)
);

CREATE INDEX IF NOT EXISTS deposit_records_proxy_idx
  ON public.deposit_records (proxy_address, chain_id, token_address);
CREATE INDEX IF NOT EXISTS deposit_records_wallet_idx
  ON public.deposit_records (wallet_address);
CREATE INDEX IF NOT EXISTS deposit_records_block_idx
  ON public.deposit_records (block_number DESC);

ALTER TABLE public.deposit_records ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'deposit_records'
      AND policyname = 'Service can manage deposit records'
  ) THEN
    CREATE POLICY "Service can manage deposit records" ON public.deposit_records
      FOR ALL USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;
