-- Create markets_map table if not exists
CREATE TABLE IF NOT EXISTS public.markets_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id BIGINT NOT NULL,
  chain_id BIGINT NOT NULL,
  market TEXT NOT NULL,
  collateral_token TEXT,
  tick_size NUMERIC,
  fee_bps SMALLINT NOT NULL DEFAULT 40,
  resolution_time TIMESTAMPTZ,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(event_id, chain_id)
);

-- Enable RLS
ALTER TABLE public.markets_map ENABLE ROW LEVEL SECURITY;

-- Add policies if they don't exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'markets_map' AND policyname = 'Public read access') THEN
    CREATE POLICY "Public read access" ON public.markets_map FOR SELECT USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'markets_map' AND policyname = 'Public insert access') THEN
    CREATE POLICY "Public insert access" ON public.markets_map FOR INSERT WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'markets_map' AND policyname = 'Public update access') THEN
    CREATE POLICY "Public update access" ON public.markets_map FOR UPDATE USING (true);
  END IF;
END $$;

-- Insert the market from deployment_clob_amoy.json for event_id=1
INSERT INTO public.markets_map (event_id, chain_id, market, collateral_token, tick_size, status)
VALUES (
  1, 
  80002, 
  '0x8b2aE97451d5773319b9d3480A71b010a544A10b', 
  '0xdc85e8303CD81e8E78f432bC2c0D673Abccd7Daf', 
  1,
  'open'
)
ON CONFLICT (event_id, chain_id) 
DO UPDATE SET 
  market = EXCLUDED.market,
  collateral_token = EXCLUDED.collateral_token;
