-- Drop existing tables if they exist
DROP TABLE IF EXISTS public.flag_settlements CASCADE;
DROP TABLE IF EXISTS public.flag_checkins CASCADE;
DROP TABLE IF EXISTS public.flag_witnesses CASCADE; -- Dropping this as it seems replaced by witness_id in flags
DROP TABLE IF EXISTS public.flags CASCADE;

-- 1. flags
CREATE TABLE public.flags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prediction_id BIGINT REFERENCES public.predictions(id) ON DELETE SET NULL,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  deadline TIMESTAMPTZ NOT NULL,
  verification_type TEXT NOT NULL CHECK (verification_type IN ('self', 'witness')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'pending_review', 'success', 'failed')),
  proof_comment TEXT,
  proof_image_url TEXT,
  witness_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flags_prediction_id_created ON public.flags (prediction_id, created_at DESC);

-- 2. flag_checkins
CREATE TABLE public.flag_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flag_id BIGINT NOT NULL REFERENCES public.flags(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL,
  note TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  review_status TEXT DEFAULT 'pending' CHECK (review_status IN ('pending', 'approved', 'rejected')),
  reviewer_id TEXT,
  review_reason TEXT,
  reviewed_at TIMESTAMPTZ
);

-- 3. flag_settlements
CREATE TABLE public.flag_settlements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flag_id BIGINT NOT NULL REFERENCES public.flags(id) ON DELETE CASCADE,
  status TEXT NOT NULL CHECK (status IN ('success', 'failed')),
  strategy TEXT,
  metrics JSONB,
  settled_by TEXT,
  settled_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.flags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flag_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.flag_settlements ENABLE ROW LEVEL SECURITY;

-- Policies
-- flags
CREATE POLICY "Flags are viewable by everyone" ON public.flags FOR SELECT USING (true);
CREATE POLICY "Users can create flags" ON public.flags FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update flags" ON public.flags FOR UPDATE USING (true);

-- flag_checkins
CREATE POLICY "Checkins are viewable by everyone" ON public.flag_checkins FOR SELECT USING (true);
CREATE POLICY "Users can create checkins" ON public.flag_checkins FOR INSERT WITH CHECK (true);
CREATE POLICY "Users can update checkins" ON public.flag_checkins FOR UPDATE USING (true);

-- flag_settlements
CREATE POLICY "Settlements are viewable by everyone" ON public.flag_settlements FOR SELECT USING (true);
CREATE POLICY "Users can create settlements" ON public.flag_settlements FOR INSERT WITH CHECK (true);

-- Realtime
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'flags') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.flags;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'flag_checkins') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.flag_checkins;
  END IF;
   IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'flag_settlements') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.flag_settlements;
  END IF;
END $$;
