export const SQL_CREATE_EVENT_FOLLOWS_TABLE = `
CREATE TABLE IF NOT EXISTS public.event_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  event_id BIGINT NOT NULL REFERENCES public.predictions(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, event_id)
);
ALTER TABLE public.event_follows ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations on event_follows" ON public.event_follows
FOR ALL USING (true) WITH CHECK (true);`;

export const SQL_FIX_USER_ID_AND_UNIQUE = `
ALTER TABLE public.event_follows ALTER COLUMN user_id TYPE TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS event_follows_user_id_event_id_key ON public.event_follows (user_id, event_id);`;

export const SQL_DROP_USER_ID_FK = `
ALTER TABLE public.event_follows DROP CONSTRAINT IF EXISTS event_follows_user_id_fkey;`;

export const SQL_FIX_USER_ID_TYPE_ONLY = `
ALTER TABLE public.event_follows ALTER COLUMN user_id TYPE TEXT;`;
